added login functionality and logout functionality.
tony1542/fast-food-simple pull request #54
Opened 2022-06-12 00:39 UTC by KizeKaze

adjusted nav ui for logged in users and when users are not logged in fixes #50

2022-06-12 19:12 UTC, tony1542 requested changes

2022-06-12 19:12 UTC, tony1542 commented on logout.php
> +session_start();
session start should only be called once. the one in your header is good! you can remove this one

2022-06-13 00:47 UTC, KizeKaze commented on logout.php
> +session_start();
Yes sir

2022-06-13 15:42 UTC, tony1542 approved these changes

2022-06-13 15:42 UTC, merged