Ui51
tony1542/fast-food-simple pull request #59
Opened 2022-06-14 23:30 UTC by KizeKaze

fixes #51

2022-06-14 23:47 UTC, tony1542 requested changes

2022-06-14 23:47 UTC, tony1542 commented on index.php
> + echo $_SESSION['user_role'];
hahe

2022-06-15 00:45 UTC, KizeKaze commented on index.php
> + echo $_SESSION['user_role'];
beat you to the punch haHe

2022-06-15 00:56 UTC, tony1542 approved these changes

2022-06-15 00:56 UTC, merged