Unittesting
tony1542/fast-food-simple pull request #75
Opened 2022-06-25 23:44 UTC by KizeKaze

added unittesting and tested every function known to man

2022-06-25 23:44 UTC, KizeKaze commented
fixes #68

2022-06-26 00:00 UTC, tony1542 requested changes
There are hard-coded values in here that aren't in the `seed.sql` script so it isn't  guaranteed they will exist by the time the tests are ran. could you update the `seed.sql` with some dummy data and refer to those records in the unit tests?

2022-06-26 00:18 UTC, tony1542 commented on database_seed.sql
> +INSERT INTO fast_food.item (name, description, cost, type_id) VALUES ('Coffee', '942 MG of caffine', 0.69, 9);
lol

2022-06-26 00:30 UTC, tony1542 requested changes

2022-06-26 00:30 UTC, tony1542 commented on tests/MenuTest.php
> +        $sql = 'SELECT MAX(id) AS item_id FROM item';
This starting query isn't helpful for the rest of the this unit test and can be stripped away

2022-06-26 00:30 UTC, tony1542 commented on tests/MenuTest.php
> +        $sql = "SELECT name FROM item WHERE id = $inserted_id";
You should be grabbing each of the 4 columns that were updated in the `updateItem()` call and asserting them as well here

2022-06-26 00:42 UTC, KizeKaze commented
forgot 4 functions in menu.php

2022-06-28 23:59 UTC, tony1542 approved these changes
Had to run `$ "vendor/bin/phpunit" tests --bootstrap ./vendor/autoload.php`, got 100% passing. good job

2022-06-28 23:59 UTC, merged